name: Periodic Health Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@e7d5ebdc9027fbf494d2d034f3e8fc78f8b7a2b9
        with:
          # Check the following URLs one by one sequentially
          url: https://fs-pokedex-e2cf.onrender.com/health|https://fs-pokedex-e2cf.onrender.com
          # Follow redirects, or just report success on 3xx status codes
          follow-redirect: false # Optional, defaults to "false"
          # Fail this action after this many failed attempts
          max-attempts: 3 # Optional, defaults to 1
          # Delay between retries
          retry-delay: 10s # Optional, only applicable to max-attempts > 1
          # Retry all errors, including 404. This option might trigger curl upgrade.
          retry-all: false # Optional, defaults to "false"
          # String representation of cookie attached to health check request.
          # Format: `Name=Value`
          #cookie: "token=asdf1234" # Optional, default is empty
          # Basic auth login password pair.
          # Format: `login:password`
          #basic-auth: "login:password" # Optional, default is empty
